// Generates src/lib/contracts/abis.ts from the Foundry build artifacts in contracts/out.
// Run `forge build` in contracts/ first. The deployed contracts were built from the same sources
// (commit 35ba3a6, solc 0.8.30), so these are the deployed ABIs, not hand-written copies.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const out = resolve(here, '../../../contracts/out')
const target = resolve(here, '../src/lib/contracts/abis.ts')

const contracts = {
  providerRegistryAbi: 'ProviderRegistry',
  serviceMarketplaceAbi: 'ServiceMarketplace',
  clinovaEscrowAbi: 'ClinovaEscrow',
  proofOfServiceAbi: 'ProofOfService',
  reputationRegistryAbi: 'ReputationRegistry',
}

const signature = (item) => `${item.name}(${item.inputs.map((i) => i.type).join(',')})`

let body = ''
const errors = new Map()
for (const [exportName, contract] of Object.entries(contracts)) {
  const artifact = JSON.parse(readFileSync(resolve(out, `${contract}.sol`, `${contract}.json`), 'utf8'))
  body += `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const\n\n`
  for (const item of artifact.abi) if (item.type === 'error') errors.set(signature(item), item)
}
// Every custom error from all five contracts, de-duplicated by signature. Used to decode reverts that bubble up
// from a module the called contract invoked (e.g. ProviderNotEligible from the registry during acceptRequest).
body += `export const clinovaErrorsAbi = ${JSON.stringify([...errors.values()], null, 2)} as const\n`

writeFileSync(
  target,
  `// GENERATED by scripts/sync-abis.mjs from contracts/out. Do not edit by hand.\n\n${body}`,
)
console.log(`wrote ${target} (${Object.keys(contracts).length} contracts, ${errors.size} errors)`)
